"""Run both baselines walk-forward over the training period and report.

    uv run python -m src.forecasting.run_baselines
    uv run python -m src.forecasting.run_baselines --last-days 30   # quick check

A quick run writes to ``data/processed/forecasts/quick/`` and prints its report.

Writes each baseline's forecasts to ``data/processed/forecasts/`` and, for a full
run, the results table to ``docs/results/phase1_baselines.md``. The hold-out is
never touched.
"""

from __future__ import annotations

import argparse
import json
import time
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

from src.config import REPO_ROOT, Settings, load_settings
from src.forecasting.baselines import build_baselines
from src.forecasting.evaluate import segment_scores, yearly_scores
from src.forecasting.walkforward import day_range, run_walk_forward

__all__ = ["main", "render_report"]

RESULTS_PATH = REPO_ROOT / "docs" / "results" / "phase1_baselines.md"
DISPLAY_NAMES = {
    "naive_previous_day": "Naive, previous day",
    "seasonal_naive_previous_week": "Seasonal naive, previous week",
}
METRIC_ORDER = [
    "days",
    "periods",
    "missing actuals",
    "mean pinball",
    "MAE of median",
    "RMSE of median",
    "bias of median",
    "coverage 50%",
    "width 50%",
    "coverage 80%",
    "width 80%",
    "coverage 90%",
    "width 90%",
]


def _format(metric: str, value: object) -> str:
    if not isinstance(value, float | int) or pd.isna(value):
        return "n/a"
    if metric in ("days", "periods", "missing actuals"):
        return f"{int(value):,}"
    if metric.startswith("coverage"):
        return f"{value:.1%}"
    return f"{value:.2f}"


def _markdown(frame: pd.DataFrame, first_header: str) -> str:
    header = [first_header, *(str(c) for c in frame.columns)]
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for label, row in frame.iterrows():
        lines.append(
            "| " + " | ".join([str(label), *(str(v) for v in row.tolist())]) + " |"
        )
    return "\n".join(lines)


def _formatted_segments(forecasts: pd.DataFrame, settings: Settings) -> pd.DataFrame:
    raw = segment_scores(forecasts, settings).T.reindex(METRIC_ORDER)
    return pd.DataFrame(
        {
            col: [_format(str(m), raw.at[m, col]) for m in raw.index]
            for col in raw.columns
        },
        index=raw.index,
    )


def _per_day_total(forecasts: pd.DataFrame, column: str) -> int:
    """Sum a per-day count that the harness repeats on every period of the day."""
    return int(forecasts[column].groupby(forecasts["target_day"]).first().sum())


def render_report(
    runs: dict[str, tuple[pd.DataFrame, float]], settings: Settings, days: list[date]
) -> str:
    quantiles = settings.forecasting.quantiles
    sections = [
        "# Phase 1 baseline results",
        "",
        "Generated by `python -m src.forecasting.run_baselines`. Walk-forward: one",
        "forecast per local day, issued at "
        f"{settings.market.forecast_issue_local} on the day before, using only",
        "information published by then. Prices and errors in €/MWh; widths are the",
        "average distance between the interval bounds.",
        "",
        f"Target days {days[0]} to {days[-1]}, {len(days):,} days. The hold-out, from "
        f"{settings.evaluation.holdout_start}, is not used.",
    ]
    for name, (forecasts, _) in runs.items():
        sections += ["", f"## {DISPLAY_NAMES.get(name, name)}", ""]
        sections.append(_markdown(_formatted_segments(forecasts, settings), "metric"))

    yearly = {}
    for name, (forecasts, _) in runs.items():
        scores = yearly_scores(forecasts, quantiles)
        label = DISPLAY_NAMES.get(name, name)
        yearly[f"{label}: mean pinball"] = scores["mean pinball"].map(
            lambda v: f"{v:.2f}"
        )
        yearly[f"{label}: coverage 90%"] = scores["coverage 90%"].map(
            lambda v: f"{v:.1%}"
        )
    sections += ["", "## By year", "", _markdown(pd.DataFrame(yearly), "year")]

    facts: dict[str, dict[str, str]] = {}
    for name, (forecasts, seconds) in runs.items():
        fallback = _per_day_total(forecasts, "fallback_periods")
        crossings = _per_day_total(forecasts, "crossings_repaired")
        facts[DISPLAY_NAMES.get(name, name)] = {
            "forecast days": f"{forecasts['target_day'].nunique():,}",
            "periods with a fallback point forecast": f"{fallback:,}",
            "periods with repaired quantile crossings": f"{crossings:,}",
            "run time, seconds": f"{seconds:.0f}",
        }
    sections += ["", "## Run facts", "", _markdown(pd.DataFrame(facts), "fact"), ""]
    return "\n".join(sections)


def _positive_int(value: str) -> int:
    number = int(value)
    if number < 1:
        raise argparse.ArgumentTypeError("must be a whole number of at least 1")
    return number


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the baselines walk-forward.")
    parser.add_argument("--config", type=Path, default=None, help="settings YAML path")
    parser.add_argument(
        "--last-days",
        type=_positive_int,
        default=None,
        help="only the last N training days",
    )
    args = parser.parse_args(argv)

    settings = load_settings(args.config)
    frame = pd.read_parquet(settings.data.dataset_path)
    last_day = settings.evaluation.holdout_start - timedelta(days=1)
    days = day_range(settings.evaluation.first_target_day, last_day)
    quick = args.last_days is not None
    if quick:
        days = days[-args.last_days :]

    out_dir = settings.data.processed_path / "forecasts"
    if quick:
        out_dir = out_dir / "quick"  # never overwrite a full run's files
    out_dir.mkdir(parents=True, exist_ok=True)
    runs: dict[str, tuple[pd.DataFrame, float]] = {}
    for model in build_baselines(settings):
        started = time.perf_counter()
        forecasts = run_walk_forward(frame, model, days, settings)
        seconds = time.perf_counter() - started
        forecasts.to_parquet(out_dir / f"{model.name}.parquet")
        runs[model.name] = (forecasts, seconds)
        print(f"{model.name}: {len(days)} days in {seconds:.0f} s")

    report = render_report(runs, settings, days)
    metrics = {
        name: segment_scores(forecasts, settings).to_dict(orient="index")
        for name, (forecasts, _) in runs.items()
    }
    (out_dir / "baseline_metrics.json").write_text(
        json.dumps(metrics, indent=2, default=str), encoding="utf-8"
    )
    if quick:
        print(report)
    else:
        RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)
        RESULTS_PATH.write_text(report, encoding="utf-8")
        print(f"wrote {RESULTS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
